### PR TITLE
change l10n to i18n methods.

### LINKED ISSUE #9: WP 5.5 - Cannot update plugins from Plugins > Add New > BoldGrid
When I have an out of date plugin showing on this page, there is a text link to update but clicking it doesn't do anything

Uncaught TypeError: wp.updates.l10n is undefined
    _updateLinks https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/boldgrid-inspirations/vendor/boldgrid/plugin-installer/src/assets/js/plugin-installer.js?ver=5.5-beta3-48551:262
    jQuery 2
    dispatch
    handle

### LINKED ISSUE #11: WP 5.5 - Cannot install plugins from Plugins > Add New > BoldGrid
All the BG plugins are listed on this page, and I should be able to install and activate them from this screen. 
image

When I click install nothing happens, this is the console error:

Uncaught TypeError: wp.updates.l10n is undefined
    _buttons https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/boldgrid-inspirations/vendor/boldgrid/plugin-installer/src/assets/js/plugin-installer.js?ver=5.5-beta3-48551:345
jQuery 2
    dispatch
    handle

If I already have a plugin installed but not active, I can activate it without error.

### PR DESCRIPTION
**Pull request by jamesros161**
change the l10n methods to use i18n methods for wp5.5 compatibility

### CODE REVIEW

**Review by cssjoe — CHANGES_REQUESTED** [review]
Use a text domain.
`__( '__', 'boldgrid-plugin-installer' );`
See https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/

**Comment by jamesros161** [comment]
Since this is a separate library, should we really use the domian 'boldgrid-plugin-installer' or should we use the text domain of boldgrid-inspirations? What other plugins use this library?

**Comment by cssjoe** [comment]
I didn't see any information regarding omitting the text domain.  The link above includes comments recommending the use.
It appears that the use of `wp-i18n` requires the dependency `wp-i18n` to be added in the `wp_register_script` call -- https://github.com/BoldGrid/plugin-installer/blob/wp55update/src/Plugin/Installer.php#L559-L567

**Comment by bwmarkle** [comment]
> Since this is a separate library, should we really use the domian 'boldgrid-plugin-installer' or should we use the text domain of boldgrid-inspirations? What other plugins use this library?

As you can see here https://github.com/BoldGrid/plugin-installer/commit/c4d68c1102af7926088306f4c4ff3b261b1db743 initially we used `boldgrid-library` and then we changed it to `boldgrid-plugin-installer`

No other plugin is really going to use this... There's probably bigger frish to fry, how about we stick with the current text domain unless there's a good reason to change it?

**Review by cssjoe — APPROVED** [review]

**Pull request merged**
